### ISSUE TITLE
Failing with the `removeListeners is not defined` error

### ISSUE THREAD

**Issue by zeekhuge** [williamkapke/irc-connect#12]
I tried the package and I am getting this error : 

 ```
 irc:connect-parsed {"nick":"NickServ","user":"NickServ","host":"services.","command":"NOTICE","params":["AlfredTheBot","You are now identified for \u0002AlfredTheBot\u0002."]} +4s
core event 'identified' triggerd :  AlfredTheBot
  irc:connect-out JOIN #thechannel +4s
  user: 'NickServ',
  host: 'services.',
  command: 'NOTICE',
  params:
   [ 'AlfredTheBot',
     'You are now identified for \u0002AlfredTheBot\u0002.' ] }
/home/zeekhuge/node_modules/irc-connect/nick.js:42
                                removeListeners.call(this);
                                ^

ReferenceError: removeListeners is not defined
    at Client.authd (/home/zeekhuge/node_modules/irc-connect/nick.js:42:5)
    at emitOne (events.js:82:20)
    at Client.emit (events.js:169:7)
    at Client.ondata (/home/zeekhuge/node_modules/irc-connect/connect.js:144:8)
    at Transformer._pushline (/home/zeekhuge/node_modules/irc-connect/node_modules/eachline/eachline.js:157:16)
    at Immediate._onImmediate (/home/zeekhuge/node_modules/irc-connect/node_modules/eachline/eachline.js:127:11)
    at processImmediate [as _immediateCallback] (timers.js:396:17)

```

**Comment by zeekhuge** [comment]
Debug data : 
 ```
....
 irc:connect-raw :NickServ!NickServ@services. NOTICE AlfredTheBot :This nickname is registered. Please choose a different nickname, or identify via /msg NickServ identify <password>. +0ms
  irc:connect-parsed {"nick":"NickServ","user":"NickServ","host":"services.","command":"NOTICE","params":["AlfredTheBot","This nickname is registered. Please choose a different nickname, or identify via \u0002/msg NickServ identify <password>\u0002."]} +0ms
  irc:connect-out PRIVMSG NickServ :IDENTIFY AlfredTheBot **************** +314ms
  irc:connect-raw :NickServ!NickServ@services. NOTICE AlfredTheBot :You are now identified for AlfredTheBot. +5s
  irc:connect-parsed {"nick":"NickServ","user":"NickServ","host":"services.","command":"NOTICE","params":["AlfredTheBot","You are now identified for \u0002AlfredTheBot\u0002."]} +5s
  irc:connect-out JOIN #sudoNerd2 +5s
/home/zeekhuge/node_modules/irc-connect/nick.js:42
				removeListeners.call(this);
				^

ReferenceError: removeListeners is not defined
    at Client.authd (/home/zeekhuge/node_modules/irc-connect/nick.js:42:5)
    at emitOne (events.js:82:20)
    at Client.emit (events.js:169:7)
    at Client.ondata (/home/zeekhuge/node_modules/irc-connect/connect.js:144:8)
    at Transformer._pushline (/home/zeekhuge/node_modules/irc-connect/node_modules/eachline/eachline.js:157:16)
    at Immediate._onImmediate (/home/zeekhuge/node_modules/irc-connect/node_modules/eachline/eachline.js:127:11)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```
